title: Naim's Hub
description: A dark, fast personal hub
markdown: kramdown
permalink: pretty

# keep this if you see it
# theme: jekyll-theme-primer

collections:
  articles:
    output: true
    permalink: /articles/:title/

defaults:
  - scope: { path: "", type: "articles" }
    values: { layout: item }
