deploy-preview:
  if: github.event_name == 'pull_request'
  needs: build
  environment:
    name: preview
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  steps:
    - id: deployment
      uses: actions/deploy-pages@v4
